[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
providers = ["node", "php"]

[build.nixpacksConfig.phases.setup]
nixPkgs = ["nodejs_20", "npm", "php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.bcmath", "php82Extensions.mbstring", "php82Extensions.gd"]

[build.buildCommand]
cmd = "npm ci && npm run build && composer install --no-dev --optimize-autoloader"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
